"""rename_transect_to_location

Revision ID: 772dd28ce3c1
Revises: bc4cf367234d
Create Date: 2025-11-12 20:31:21.095034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '772dd28ce3c1'
down_revision: Union[str, Sequence[str], None] = 'bc4cf367234d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # FIXED: Use rename_table instead of drop/create to preserve data
    op.rename_table('transect', 'location')

    # Rename transect_id column to location_id in sighting table
    op.alter_column('sighting', 'transect_id', new_column_name='location_id')

    # Update nullability constraints
    op.alter_column('sighting', 'species_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sighting', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # Update foreign keys to reflect new table and column names
    op.drop_constraint(op.f('sighting_species_id_fkey'), 'sighting', type_='foreignkey')
    op.drop_constraint(op.f('sighting_survey_id_fkey'), 'sighting', type_='foreignkey')
    op.drop_constraint(op.f('sighting_transect_id_fkey'), 'sighting', type_='foreignkey')
    op.create_foreign_key(None, 'sighting', 'survey', ['survey_id'], ['id'])
    op.create_foreign_key(None, 'sighting', 'species', ['species_id'], ['id'])
    op.create_foreign_key(None, 'sighting', 'location', ['location_id'], ['id'])

    # Keep created_at columns (removed drop operations)
    op.drop_constraint(op.f('species_name_type_key'), 'species', type_='unique')
    # Note: Keeping survey.notes as TEXT (no type change needed)
    op.alter_column('survey_surveyor', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('survey_surveyor', 'surveyor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('survey_surveyor_survey_id_surveyor_id_key'), 'survey_surveyor', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep created_at columns (removed add operations in downgrade)
    op.create_unique_constraint(op.f('survey_surveyor_survey_id_surveyor_id_key'), 'survey_surveyor', ['survey_id', 'surveyor_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('survey_surveyor', 'surveyor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('survey_surveyor', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # Note: Keeping survey.notes as TEXT (no type change needed in downgrade)
    op.create_unique_constraint(op.f('species_name_type_key'), 'species', ['name', 'type'], postgresql_nulls_not_distinct=False)
    # Note: We're not adding back transect_id since we renamed it, not dropping it
    op.drop_constraint(None, 'sighting', type_='foreignkey')
    op.drop_constraint(None, 'sighting', type_='foreignkey')
    op.drop_constraint(None, 'sighting', type_='foreignkey')
    op.create_foreign_key(op.f('sighting_transect_id_fkey'), 'sighting', 'transect', ['transect_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('sighting_survey_id_fkey'), 'sighting', 'survey', ['survey_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('sighting_species_id_fkey'), 'sighting', 'species', ['species_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sighting', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sighting', 'species_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # Restore location_id column name to transect_id
    op.alter_column('sighting', 'location_id', new_column_name='transect_id')

    # Restore location table name to transect
    op.rename_table('location', 'transect')
    # ### end Alembic commands ###
